package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STUDENT".
 */
public class student {

    /** Not-null value. */
    private String name;
    private int point;
    /** Not-null value. */
    private String kinds;

    public student() {
    }

    public student(String name, int point, String kinds) {
        this.name = name;
        this.point = point;
        this.kinds = kinds;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getPoint() {
        return point;
    }

    public void setPoint(int point) {
        this.point = point;
    }

    /** Not-null value. */
    public String getKinds() {
        return kinds;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKinds(String kinds) {
        this.kinds = kinds;
    }

}
